// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idr.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDR struct {
	UserId               *ID      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose              string   `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Context              string   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	BusinessId           string   `protobuf:"bytes,4,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Authtoken            string   `protobuf:"bytes,5,opt,name=authtoken,proto3" json:"authtoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDR) Reset()         { *m = IDR{} }
func (m *IDR) String() string { return proto.CompactTextString(m) }
func (*IDR) ProtoMessage()    {}
func (*IDR) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{0}
}

func (m *IDR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDR.Unmarshal(m, b)
}
func (m *IDR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDR.Marshal(b, m, deterministic)
}
func (m *IDR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDR.Merge(m, src)
}
func (m *IDR) XXX_Size() int {
	return xxx_messageInfo_IDR.Size(m)
}
func (m *IDR) XXX_DiscardUnknown() {
	xxx_messageInfo_IDR.DiscardUnknown(m)
}

var xxx_messageInfo_IDR proto.InternalMessageInfo

func (m *IDR) GetUserId() *ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *IDR) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *IDR) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *IDR) GetBusinessId() string {
	if m != nil {
		return m.BusinessId
	}
	return ""
}

func (m *IDR) GetAuthtoken() string {
	if m != nil {
		return m.Authtoken
	}
	return ""
}

type ID struct {
	Piiid                string   `protobuf:"bytes,6,opt,name=piiid,proto3" json:"piiid,omitempty"`
	CompleteName         string   `protobuf:"bytes,7,opt,name=complete_name,json=completeName,proto3" json:"complete_name,omitempty"`
	AadUserName          string   `protobuf:"bytes,8,opt,name=aad_user_name,json=aadUserName,proto3" json:"aad_user_name,omitempty"`
	EntityId             string   `protobuf:"bytes,9,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityName           string   `protobuf:"bytes,10,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Address              string   `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	Postcode             string   `protobuf:"bytes,12,opt,name=postcode,proto3" json:"postcode,omitempty"`
	City                 string   `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,14,opt,name=province,proto3" json:"province,omitempty"`
	Country              string   `protobuf:"bytes,15,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{1}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPiiid() string {
	if m != nil {
		return m.Piiid
	}
	return ""
}

func (m *ID) GetCompleteName() string {
	if m != nil {
		return m.CompleteName
	}
	return ""
}

func (m *ID) GetAadUserName() string {
	if m != nil {
		return m.AadUserName
	}
	return ""
}

func (m *ID) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *ID) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *ID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ID) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *ID) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ID) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *ID) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type IDRes struct {
	UserId               *ID      `protobuf:"bytes,16,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Result               string   `protobuf:"bytes,17,opt,name=result,proto3" json:"result,omitempty"`
	Pack                 *Pack    `protobuf:"bytes,18,opt,name=pack,proto3" json:"pack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRes) Reset()         { *m = IDRes{} }
func (m *IDRes) String() string { return proto.CompactTextString(m) }
func (*IDRes) ProtoMessage()    {}
func (*IDRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{2}
}

func (m *IDRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRes.Unmarshal(m, b)
}
func (m *IDRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRes.Marshal(b, m, deterministic)
}
func (m *IDRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRes.Merge(m, src)
}
func (m *IDRes) XXX_Size() int {
	return xxx_messageInfo_IDRes.Size(m)
}
func (m *IDRes) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRes.DiscardUnknown(m)
}

var xxx_messageInfo_IDRes proto.InternalMessageInfo

func (m *IDRes) GetUserId() *ID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *IDRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *IDRes) GetPack() *Pack {
	if m != nil {
		return m.Pack
	}
	return nil
}

type Pack struct {
	ExpiryTime           int64    `protobuf:"varint,19,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	Certificate          []byte   `protobuf:"bytes,20,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey           *PK      `protobuf:"bytes,21,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pack) Reset()         { *m = Pack{} }
func (m *Pack) String() string { return proto.CompactTextString(m) }
func (*Pack) ProtoMessage()    {}
func (*Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{3}
}

func (m *Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pack.Unmarshal(m, b)
}
func (m *Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pack.Marshal(b, m, deterministic)
}
func (m *Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pack.Merge(m, src)
}
func (m *Pack) XXX_Size() int {
	return xxx_messageInfo_Pack.Size(m)
}
func (m *Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_Pack proto.InternalMessageInfo

func (m *Pack) GetExpiryTime() int64 {
	if m != nil {
		return m.ExpiryTime
	}
	return 0
}

func (m *Pack) GetCertificate() []byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *Pack) GetPrivateKey() *PK {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

type PK struct {
	Secret               string   `protobuf:"bytes,22,opt,name=secret,proto3" json:"secret,omitempty"`
	Key                  []byte   `protobuf:"bytes,23,opt,name=key,proto3" json:"key,omitempty"`
	Pfx                  []byte   `protobuf:"bytes,24,opt,name=pfx,proto3" json:"pfx,omitempty"`
	Kty                  string   `protobuf:"bytes,25,opt,name=kty,proto3" json:"kty,omitempty"`
	Purposes             []string `protobuf:"bytes,26,rep,name=purposes,proto3" json:"purposes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK) Reset()         { *m = PK{} }
func (m *PK) String() string { return proto.CompactTextString(m) }
func (*PK) ProtoMessage()    {}
func (*PK) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{4}
}

func (m *PK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK.Unmarshal(m, b)
}
func (m *PK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK.Marshal(b, m, deterministic)
}
func (m *PK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK.Merge(m, src)
}
func (m *PK) XXX_Size() int {
	return xxx_messageInfo_PK.Size(m)
}
func (m *PK) XXX_DiscardUnknown() {
	xxx_messageInfo_PK.DiscardUnknown(m)
}

var xxx_messageInfo_PK proto.InternalMessageInfo

func (m *PK) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PK) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PK) GetPfx() []byte {
	if m != nil {
		return m.Pfx
	}
	return nil
}

func (m *PK) GetKty() string {
	if m != nil {
		return m.Kty
	}
	return ""
}

func (m *PK) GetPurposes() []string {
	if m != nil {
		return m.Purposes
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_091ce7462bfddb75, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IDR)(nil), "idrproto.IDR")
	proto.RegisterType((*ID)(nil), "idrproto.ID")
	proto.RegisterType((*IDRes)(nil), "idrproto.IDRes")
	proto.RegisterType((*Pack)(nil), "idrproto.Pack")
	proto.RegisterType((*PK)(nil), "idrproto.PK")
	proto.RegisterType((*Empty)(nil), "idrproto.Empty")
}

func init() { proto.RegisterFile("idr.proto", fileDescriptor_091ce7462bfddb75) }

var fileDescriptor_091ce7462bfddb75 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0x9f, 0x49, 0xd2, 0x9f, 0xa5, 0x94, 0xa5, 0x20, 0x11, 0x19, 0x21, 0x45, 0x48,
	0xf4, 0x50, 0xe0, 0x05, 0xc0, 0x08, 0xac, 0x4a, 0x55, 0x64, 0xe0, 0xc2, 0x25, 0xda, 0x7a, 0x27,
	0x65, 0x49, 0x62, 0xaf, 0x76, 0xd7, 0x21, 0x7e, 0x1a, 0xc4, 0xc3, 0xf1, 0x1e, 0xc8, 0xb3, 0xb6,
	0x5a, 0x38, 0x54, 0x70, 0x9b, 0xef, 0x67, 0x66, 0xe7, 0xc7, 0x86, 0xa1, 0x92, 0xe6, 0x4c, 0x9b,
	0xdc, 0xe5, 0x6c, 0xa0, 0xa4, 0xa1, 0x28, 0xfc, 0x11, 0x40, 0x3b, 0x8e, 0x12, 0xf6, 0x0c, 0xfa,
	0x85, 0x45, 0xb3, 0x50, 0x92, 0x07, 0xd3, 0x60, 0x36, 0x3a, 0x1f, 0x9f, 0x35, 0x9e, 0xb3, 0x38,
	0x4a, 0x7a, 0x95, 0x18, 0x4b, 0xc6, 0xa1, 0xaf, 0x0b, 0xa3, 0x73, 0x8b, 0xbc, 0x35, 0x0d, 0x66,
	0xc3, 0xa4, 0x81, 0x95, 0x92, 0xe6, 0x99, 0xc3, 0x9d, 0xe3, 0x6d, 0xaf, 0xd4, 0x90, 0x3d, 0x81,
	0xd1, 0x55, 0x61, 0x55, 0x86, 0xd6, 0x56, 0xe5, 0x3b, 0xa4, 0x42, 0x43, 0xc5, 0x92, 0x3d, 0x86,
	0xa1, 0x28, 0xdc, 0x57, 0x97, 0xaf, 0x30, 0xe3, 0x5d, 0x92, 0x6f, 0x88, 0xf0, 0x67, 0x0b, 0x5a,
	0x71, 0xc4, 0x8e, 0xa1, 0xab, 0x95, 0x52, 0x92, 0xf7, 0xc8, 0xe0, 0x01, 0x7b, 0x0a, 0x93, 0x34,
	0xdf, 0xe8, 0x35, 0x3a, 0x5c, 0x64, 0x62, 0x83, 0xbc, 0x4f, 0xea, 0xb8, 0x21, 0x2f, 0xc5, 0x06,
	0x59, 0x08, 0x13, 0x21, 0xe4, 0x82, 0xe6, 0x23, 0xd3, 0x80, 0x4c, 0x23, 0x21, 0xe4, 0x67, 0x8b,
	0x86, 0x3c, 0x8f, 0x60, 0x88, 0x99, 0x53, 0xae, 0xac, 0x5a, 0x1c, 0x92, 0x3e, 0xf0, 0x44, 0x2c,
	0xab, 0x09, 0x6a, 0x91, 0xd2, 0xc1, 0x4f, 0xe0, 0x29, 0xca, 0xe6, 0xd0, 0x17, 0x52, 0x1a, 0xb4,
	0x96, 0x8f, 0xfc, 0xf0, 0x35, 0x64, 0xa7, 0x30, 0xd0, 0xb9, 0x75, 0x69, 0x2e, 0x91, 0x8f, 0x7d,
	0xd9, 0x06, 0x33, 0x06, 0x9d, 0x54, 0xb9, 0x92, 0x4f, 0x88, 0xa7, 0x98, 0xfc, 0x26, 0xdf, 0xaa,
	0x2c, 0x45, 0xbe, 0x5f, 0xfb, 0x6b, 0xec, 0x57, 0x5c, 0x64, 0xce, 0x94, 0xfc, 0xa0, 0x59, 0x31,
	0xc1, 0xf0, 0x1b, 0x74, 0xe3, 0x28, 0x41, 0x7b, 0xfb, 0x8c, 0x87, 0x77, 0x9c, 0xf1, 0x04, 0x7a,
	0x06, 0x6d, 0xb1, 0x76, 0xfc, 0x88, 0x0a, 0xd5, 0x88, 0x85, 0xd0, 0xd1, 0x22, 0x5d, 0x71, 0x46,
	0xb9, 0xfb, 0x37, 0xb9, 0x73, 0x91, 0xae, 0x12, 0xd2, 0xc2, 0x1d, 0x74, 0x2a, 0x44, 0x4b, 0xd9,
	0x69, 0x65, 0xca, 0x85, 0x53, 0x1b, 0xe4, 0xf7, 0xa6, 0xc1, 0xac, 0x9d, 0x80, 0xa7, 0x3e, 0xa9,
	0x0d, 0xb2, 0x29, 0x8c, 0x52, 0x34, 0x4e, 0x2d, 0x55, 0x2a, 0x1c, 0xf2, 0xe3, 0x69, 0x30, 0x1b,
	0x27, 0xb7, 0x29, 0xf6, 0x02, 0x46, 0xda, 0xa8, 0xad, 0x70, 0xb8, 0x58, 0x61, 0xc9, 0xef, 0xff,
	0xdd, 0xf1, 0xfc, 0x22, 0x81, 0xda, 0x70, 0x81, 0x65, 0x98, 0x41, 0x6b, 0x7e, 0x51, 0xf5, 0x6e,
	0x31, 0x35, 0xe8, 0xf8, 0x89, 0xef, 0xdd, 0x23, 0x76, 0x08, 0xed, 0xaa, 0xc8, 0x03, 0x7a, 0xa6,
	0x0a, 0x2b, 0x46, 0x2f, 0x77, 0x9c, 0x7b, 0x46, 0x2f, 0x77, 0xe4, 0x71, 0x25, 0x7f, 0x48, 0x89,
	0x55, 0x48, 0xfb, 0xf6, 0x5f, 0xb0, 0xe5, 0xa7, 0xd3, 0x36, 0xed, 0xbb, 0xc6, 0x61, 0x1f, 0xba,
	0xef, 0x36, 0xda, 0x95, 0xe7, 0xbf, 0x02, 0x38, 0x89, 0xd4, 0xb5, 0x72, 0x62, 0x1d, 0x4b, 0x7f,
	0xf6, 0x8f, 0x68, 0xb6, 0x2a, 0x45, 0x76, 0x0e, 0xfb, 0x09, 0x5e, 0x2b, 0xeb, 0xd0, 0x5c, 0xe2,
	0xf7, 0x28, 0x8e, 0xd8, 0xe4, 0x8f, 0x8d, 0x9f, 0x1e, 0xdc, 0x40, 0x2a, 0x16, 0xee, 0xb1, 0xe7,
	0xd0, 0x7b, 0x8f, 0xee, 0x6e, 0x2f, 0x9d, 0x33, 0xdc, 0x63, 0xaf, 0xe0, 0x70, 0x2e, 0x8c, 0x53,
	0x62, 0x9d, 0xe0, 0x36, 0x5f, 0xe1, 0xbf, 0xbd, 0xf0, 0x1a, 0x8e, 0xde, 0xd6, 0x7f, 0xc0, 0x7f,
	0xa4, 0xbd, 0x19, 0x7f, 0x08, 0xbe, 0x0c, 0x88, 0xba, 0x2a, 0x96, 0x57, 0x3d, 0x8a, 0x5e, 0xfe,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x36, 0xd7, 0xde, 0x51, 0x38, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DigitalIdentityServiceClient is the client API for DigitalIdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DigitalIdentityServiceClient interface {
	RegisterNewDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error)
	GetDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*IDRes, error)
	PartialRevokeDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error)
	CompleteRevokeDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error)
}

type digitalIdentityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalIdentityServiceClient(cc grpc.ClientConnInterface) DigitalIdentityServiceClient {
	return &digitalIdentityServiceClient{cc}
}

func (c *digitalIdentityServiceClient) RegisterNewDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/idrproto.DigitalIdentityService/RegisterNewDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIdentityServiceClient) GetDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*IDRes, error) {
	out := new(IDRes)
	err := c.cc.Invoke(ctx, "/idrproto.DigitalIdentityService/GetDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIdentityServiceClient) PartialRevokeDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/idrproto.DigitalIdentityService/PartialRevokeDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIdentityServiceClient) CompleteRevokeDID(ctx context.Context, in *IDR, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/idrproto.DigitalIdentityService/CompleteRevokeDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigitalIdentityServiceServer is the server API for DigitalIdentityService service.
type DigitalIdentityServiceServer interface {
	RegisterNewDID(context.Context, *IDR) (*Empty, error)
	GetDID(context.Context, *IDR) (*IDRes, error)
	PartialRevokeDID(context.Context, *IDR) (*Empty, error)
	CompleteRevokeDID(context.Context, *IDR) (*Empty, error)
}

// UnimplementedDigitalIdentityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDigitalIdentityServiceServer struct {
}

func (*UnimplementedDigitalIdentityServiceServer) RegisterNewDID(ctx context.Context, req *IDR) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewDID not implemented")
}
func (*UnimplementedDigitalIdentityServiceServer) GetDID(ctx context.Context, req *IDR) (*IDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDID not implemented")
}
func (*UnimplementedDigitalIdentityServiceServer) PartialRevokeDID(ctx context.Context, req *IDR) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartialRevokeDID not implemented")
}
func (*UnimplementedDigitalIdentityServiceServer) CompleteRevokeDID(ctx context.Context, req *IDR) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteRevokeDID not implemented")
}

func RegisterDigitalIdentityServiceServer(s *grpc.Server, srv DigitalIdentityServiceServer) {
	s.RegisterService(&_DigitalIdentityService_serviceDesc, srv)
}

func _DigitalIdentityService_RegisterNewDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIdentityServiceServer).RegisterNewDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idrproto.DigitalIdentityService/RegisterNewDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIdentityServiceServer).RegisterNewDID(ctx, req.(*IDR))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIdentityService_GetDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIdentityServiceServer).GetDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idrproto.DigitalIdentityService/GetDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIdentityServiceServer).GetDID(ctx, req.(*IDR))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIdentityService_PartialRevokeDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIdentityServiceServer).PartialRevokeDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idrproto.DigitalIdentityService/PartialRevokeDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIdentityServiceServer).PartialRevokeDID(ctx, req.(*IDR))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIdentityService_CompleteRevokeDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIdentityServiceServer).CompleteRevokeDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idrproto.DigitalIdentityService/CompleteRevokeDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIdentityServiceServer).CompleteRevokeDID(ctx, req.(*IDR))
	}
	return interceptor(ctx, in, info, handler)
}

var _DigitalIdentityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idrproto.DigitalIdentityService",
	HandlerType: (*DigitalIdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewDID",
			Handler:    _DigitalIdentityService_RegisterNewDID_Handler,
		},
		{
			MethodName: "GetDID",
			Handler:    _DigitalIdentityService_GetDID_Handler,
		},
		{
			MethodName: "PartialRevokeDID",
			Handler:    _DigitalIdentityService_PartialRevokeDID_Handler,
		},
		{
			MethodName: "CompleteRevokeDID",
			Handler:    _DigitalIdentityService_CompleteRevokeDID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idr.proto",
}
