version: "3.8"

networks:
  exp-ledger:
    external: false

services:
  rdb:
    container_name: rdb
    image: mongo:latest
    networks:
      - exp-ledger
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    environment:
      MONGO_ROOT_PWD: toor
      MONGO_INITDB_DATABASE: TestRepository
      MONGO_INITDB_ROOT_USERNAME: xqledger
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_WIREDTIGER_CACHE_SIZE_GB: '4.21'
      MONGO_EXTRA_ARGS: '--ipv6 --quiet'
    restart: always  
  

  